
// 1366 medium 通过投票对团队排名

// 现在有一个特殊的排名系统，依据参赛团队在投票人心中的次序进行排名，每个投票者都需要按从高到低的顺序对参与排名的所有团队进行排位。
//
// 排名规则如下：
//
// 参赛团队的排名次序依照其所获「排位第一」的票的多少决定。如果存在多个团队并列的情况，将继续考虑其「排位第二」的票的数量。
// 以此类推，直到不再存在并列的情况。
// 如果在考虑完所有投票情况后仍然出现并列现象，则根据团队字母的字母顺序进行排名。
// 给你一个字符串数组 votes 代表全体投票者给出的排位情况，请你根据上述排名规则对所有参赛团队进行排名。
// 请你返回能表示按排名系统 排序后 的所有团队排名的字符串。
//
//
// 示例 1：
// 输入：votes = ["ABC","ACB","ABC","ACB","ACB"]
// 输出："ACB"
// 解释：A 队获得五票「排位第一」，没有其他队获得「排位第一」，所以 A 队排名第一。
// B 队获得两票「排位第二」，三票「排位第三」。
// C 队获得三票「排位第二」，两票「排位第三」。
// 由于 C 队「排位第二」的票数较多，所以 C 队排第二，B 队排第三。

// 示例 2：
// 输入：votes = ["WXYZ","XYZW"]
// 输出："XWYZ"
// 解释：X 队在并列僵局打破后成为排名第一的团队。X 队和 W 队的「排位第一」票数一样，但是 X 队有一票「排位第二」，
// 而 W 没有获得「排位第二」。

// 示例 3：
// 输入：votes = ["ZMNAGUEDSJYLBOPHRQICWFXTVK"]
// 输出："ZMNAGUEDSJYLBOPHRQICWFXTVK"
// 解释：只有一个投票者，所以排名完全按照他的意愿。

// 示例 4：
// 输入：votes = ["BCA","CAB","CBA","ABC","ACB","BAC"]
// 输出："ABC"
// 解释：
// A 队获得两票「排位第一」，两票「排位第二」，两票「排位第三」。
// B 队获得两票「排位第一」，两票「排位第二」，两票「排位第三」。
// C 队获得两票「排位第一」，两票「排位第二」，两票「排位第三」。
// 完全并列，所以我们需要按照字母升序排名。

// 示例 5：
// 输入：votes = ["M","M","M","M"]
// 输出："M"
// 解释：只有 M 队参赛，所以它排名第一。
//  
//
// 提示：
// 1 <= votes.length <= 1000
// 1 <= votes[i].length <= 26
// votes[i].length == votes[j].length for 0 <= i, j < votes.length
// votes[i][j] 是英文 大写 字母
// votes[i] 中的所有字母都是唯一的
// votes[0] 中出现的所有字母 同样也 出现在 votes[j] 中，其中 1 <= j < votes.length



var rankTeams = function(votes) {
    if (!votes.length) return '';
    if (votes.length === 1) return votes[0];
    // 如果只有一个队伍
    if(votes[0].length === 1) return votes[0];

    let arr = [];
    for(let i = 0; i < votes[0].length; i++){
        arr[i] = {
            key: votes[0][i],
            val: ''
        }
    }
    for(let i = 0; i < votes[0].length; i++){
        let hash = {};
        for(let j = 0; j < votes.length; j++){
            hash[votes[j][i]] = ~~hash[votes[j][i]] + 1;
        }
        for(let k = 0; k < arr.length; k++){
            let c = hash[arr[k].key] ? hash[arr[k].key] + '': '000';
            if (c.length === 1){
                c = "00" + c;
            }else if(c.length === 2){
                c = '0' + c;
            }
            arr[k].val += c;
        }
    }
    arr.sort((a, b) => {
        if(a.val === b.val){
            return a.key > b.key ? 1: -1
        }else{
            return b.val - a.val;
        }
    });
    let res = '';
    for(let i = 0; i < arr.length; i++){
        res += arr[i].key;
    }
    return res;
};

console.log(rankTeams(["OGBDIUXYK","IBXODYUKG","GBOUIDXKY","OIXDUGBKY","UBIKDGXYO","OXIKDYUBG","BODUYKXGI","OGBDYIUXK","UIDOXGKBY","UXBDOIKYG","OGDIXBKUY","GYDIXKUOB","XIUBYOKGD","DOBYKUXGI","OUXYIDBKG","XGBOUYIKD","DKGUIXBOY","OXYDGUBIK","OIXGYBKDU","BKUDOXIYG","UIYDBOXGK","BXIODGYUK","IUYXGKDBO","XGIKDYOBU","GXOUDKBYI","XUBOIKGDY","UIXODBGYK","BKDXIGOYU","BXUIGDKYO","OGDUXYKBI","IXODKUGYB","YIBODKUXG","KXUIDOGYB","UKXBYOGDI","XBUOGYKID","GBKOUYIXD","KXUIDYBOG","OIDXKGYUB","UIDGKYXOB","KDYIXOGUB","XIYUBGKDO","IKUXDOBYG","IKODYGUBX","YKUXIOBGD","DXUBYKIGO","OKDXGBUIY","GIYKBXOUD","GUBDIYXKO","YBGDIKOUX","BDKIUXGYO","XYDGUOBKI","GDYBKUOXI","BYGKOXDIU","KDOBIGYUX","GUODKBYIX","BOUYIGKDX","GDXBIYOUK","YXGBODUKI","KGYBIUODX","DGBYOXUKI","XDBGYKUOI","KDXIBUGOY","ODUKGBXIY","IXGKBDUOY","GOKUDYIXB","IDYXBUGOK","DGYBXKOUI","OIUDXKYBG","YOGBDKXUI","BKYOIGDXU","DYIXUGKOB","GBXUYKOID","YDUOGIXBK","IKGDXUBOY","GYOIDKXUB","GIOYUDXBK","GOYUIBDKX","IXDYBOGKU","OKUIBDYXG","YIKUXDBOG","IDYUBKGOX","DXKYIUGBO","DKIXGUOYB","GYOXDKUBI","YKDIXUBOG","UOBGIKYXD","IGYOUKXBD","BYXKIDGOU","YKXOBDIGU","DYKOUBXGI","YDBKUIXOG","XUGDBYIKO","UKGDIYXBO","UKDOIXGYB","KUIDXYOBG","DXGUYBKIO","YDGIKBXOU","XUKBIDGYO","OUXIKYBDG","KBIOUDYXG","XUKYOIBGD","YXBIDUKOG","KOIUBXYDG","KUXYGOBDI","OIKUGBXYD","GKUDOBYXI","IOBXGYKDU","UBGXYOIDK","IDUBOYXKG","YDIUKXOBG","XGIKUDBOY","UIBGOYKXD","BYUGDIKOX","XYOKBIGUD","BGKXDOUIY","UGBDXYOIK","XBDOKGYUI","BUDGYKIOX","BOGUKYDIX","IOYUKXDGB","UKGYDIOXB","GBYDOXIKU","GUBIXKODY","BUOYDIKGX","DBOIXUYKG","GKOXDBYUI","IBGOKXYDU","BYKDXIGUO","KDOBIYGXU","YXDIOKUBG","YGDOIXKUB","XYDUKBIGO","GKXBYUDIO","XOGIYBUDK","BDOXKGUYI","IKXDYGUOB","YIGXDBOKU","GDYXOKIBU","KUGDIYOXB","BDYKIXUGO","GBOXUYDKI","IOBDUXKGY","GXIUBDYOK","YKBXOIUGD","BYKOXUDIG","DGXKYIUOB","OIGXBDKUY","KDGOUYBXI","UBDIGYKOX","UDGBIXYKO","BGKUOYXDI","DKGBUXIOY","XBYUDKIGO","XOYGIBKUD","DBXIKGYOU","GOBIXDUKY","IXKOUYBDG","BDXKUGOYI","GKYDBUIOX","IOXBYKGDU","OXGIDBKYU","IBXDKGUYO","UOBIXKDGY","IUKDBGYOX","BKYOXGDIU","YXGOBKDIU","YUIKDBXOG","GIKODYXBU","KBDUOIYXG","GBOKYIXUD","KIDYXGBUO","XUYIBGKOD","UBDYIXGKO","OIGUYBDKX","KYOUXIDGB","IXYUDGOBK","KGODBUYIX","GDXUBKIOY","OUGIBYXDK","KUIBODGXY","OUYBGXKDI","DBUOXKIGY","DBIYOXUKG","UKXBIGODY","YUIXBGKDO","BUOGXYDKI","DIBXYUOKG","GBXIKUYDO","GUIBDKOXY","BOGDYKUIX","YOBKUDXIG","OKIDXBUGY","BOKGYIUXD","IBGKUYODX","DXKGOBIUY","KXUBIDGOY","GXBYDKIOU","BOYIUXDGK","DKXGBIYOU","BUDIGXYOK","YKOBGXIDU","DKYIGOUXB","KDOIXUGYB","GDUIKBOYX","YDXIKOGUB","KIXOYGUDB","KYDIXOUGB","IYDOBUKXG","DGUBXIKOY","KBYDOGIXU","XGBDUYOIK","KXIUODGYB","YDGIBUKXO","YOXDGBIUK","KYBGIDUXO","YBUOIDXKG","UIOYGDBXK","KXIOGYBDU","YBOKIXGUD","GYIODBUKX","DOIXUBGKY","KXGUYIDBO","YOKBUGIDX","BIYDOXKUG","IDKOXUBYG","DBGUXKOYI","OIXKGYUDB","GKYIDBUXO","OKIXBGUYD","BOKIUDXGY","YBXGOKDUI","YBKDIOXUG","BGDUYOXIK","KDOUBIYGX","BDUOYXGIK","YDOGKIXBU","YIGOXKBDU","YDXIBOUKG","KUOGIBYXD","GIBUKXOYD","IYXOBDKUG","BOIDYUXKG","XOGBUDYIK","KYOBGDXIU","BKDOYIXUG","IDKYXGOBU","KUYGOXBDI","GDUKBIYXO","BIXYKGODU","ODUIKYXBG","DBXYGOIKU","YUDXKGOIB","XDYOKGIUB","UXIBYOKDG","DUGYXKBIO","KYUBOXDIG","KIDOGBUXY","XOYDBKUGI","OGBIUXDKY","ODYUKBXGI","XKDIYBGOU","BYXKUIGDO","KUYODXBIG","BUOYGIKXD","GOBXUYKID","YDIGOKBUX","KXIOYDGUB","BGOIXDYKU","GKYXBOUDI","OKUIDGBYX","YDGBOUXKI","KGIUDOXYB","GDKUBOIYX","YUKGBDXIO","XKDYIUBOG","BOXIUYGKD","UBKIGDXYO","IUKXGBDOY","YBIXDUOGK","GIUKDBYXO","GIKBXDOUY","XBKYUGOID","XOYUIKDBG","BXGDUYKIO","YUDGIXOKB","UIDKBYGXO","GYKOBUIDX","YKXBGOUDI","UXGIKYODB","DBIUXYGKO","KIUBGXDOY","DKUYXBIOG","IUXOYKBGD","GOKUDYXBI","OIGUDXBKY","KOIGYUDBX","XOBYIKDUG","KXDBGUOYI","OXBIKDUYG","XGYOBDKIU","UYOIGKBDX","IYDXKOBGU","IXDKGOUBY","GIBDXUYKO","GDIBOYXUK","DGYBOXUIK","GYDUKXIOB","UXYGKDOIB","BXGYUKDIO","KGOYUDIXB","DGOXYIKBU","GOYIKBDUX","IOUBXGKYD","XGIKYOBDU","IOUGKDBYX","BGIXYKUDO","UYODXBGKI","UOGBXDYKI","GBIDYXKUO","KBIUOGDXY","DGOUIXKYB","IBOKYUXDG","BDXIYOUGK","GKXUYOIDB","UOGIBKXDY","GYOUKIXDB","KYOIUGXBD","YUOBGIDKX","XIBKDGYUO","XGODUBKYI","DIYKGBUOX","YIGUODKBX","OBIKDGXUY","ODIXUKGYB","KDOGYIXUB","YOGUKIXBD","OYBUKDIXG","UGBXKYODI","XIUKYDBGO","KUIYDBGOX","YKXIODGBU","YBUKOXIGD","XBYIDKGOU","GXKDBYUIO","BUGXIYDKO","IDGUYKXBO","ODBGYXUIK","UGIDBXKOY","OGYDUBIKX","IXUKOBDYG","GIDXBKYUO","UDBGOXIKY","YDBUIOKXG","BXGYUDOKI","BIDUOYGXK","YKXGBUIOD","UGYDIOKXB","IXKUGOYBD","GKUXBYOID","YGXBIKUOD","XYKODUIBG","BKYDXOIGU","BKIODGYUX","GYUDIXOKB","KUBDOIXYG","DOYXGUIKB","XYOIBDUGK","XUDIKBYOG","IUBKXYDGO","YKODIUGXB","BXDGYOUIK","IXBUODGYK","KDGXUOYBI","UDYOKXBGI","IUBYKXGDO","BODIXKGYU","XDKGUOYBI","DKIGBOYXU","XYIKDBUOG","GOUIXBKDY","DOBKIYUXG","OXBIUDKGY","OIKXYGDUB","GKDOIUBYX","OIBXDKYUG","UIDBGXYKO","XYDOUBKIG","XUKGODBIY","GIYDOXBKU","GXBIUKYOD","BUGDIXOYK","IUOGBKYDX","IGDOBUYKX","IDKOYXGBU","OXYDKBGUI","YXUGKBIDO","YGDXUOBIK","KYUGBXIOD","UIKBOGYXD","YBIGKOUXD","ODYBXGIKU","GIDBYXUKO","XIOYKUDBG","UIYXBKODG","GKDOYBUIX","OBKGXUIDY","BDKIUXGYO","IUDBXYGOK","IYDGKOBXU","XDKBOUIYG","DOBXKGYIU","YOBXUKIDG","GIDYOUXBK","UDOYKXIGB","DYBOGUIXK","OUKXGIDYB","GUKIXYDBO","IGOXDUBKY","KDIXOGUYB","OXKDIGYUB","OXIYBGKUD","UDIYXOKBG","GOXKYIBUD","IXDBOYGUK","BKYXDIGOU","YKXGOUDBI","DBOXKGYUI","GKXYBDUIO","KXUDIYBGO","KXOBGDYUI","DIBXYOKUG","DKBGIXUOY","BUDKXYGOI","YBKGOXDIU","XUKIGOBYD","YUKDOIBXG","BUIYODKXG","YUBKOIXGD","BXDIUOKYG","GKXODYUBI","OIDUYXGBK","YDOXBGKUI","XOBYGDKUI","KUBIGDOXY","KYXBGDUOI","UOBDGYKIX","YIGUXKOBD","KOUGIYBXD","BXOUIYDKG","XKYGBOUDI","YUIGOXKDB","GIBODKYXU","GIXYKDOUB","DBXKUOYIG","IYDXGKBUO","XOGBUDYIK","UIKDBOGXY","BYIKODXGU","UXGKIDOBY","YXUBKOGDI","KUOGDXIBY","GUIDKOXBY","BYIOXGDKU","OGDXUYIKB","GUOBXDYKI","XIKBYGDOU","IKBGXUYDO","GUYIOXBKD","BUOYXDIGK","DOIBXYUKG","IXDUGOBKY","YUBIOKDXG","BYGDKUXOI","OGXUIYKDB","BKGYUODIX","OBDXIKUGY","BGIXDUOYK","IOGBYXKDU","YUKXBIOGD","BUXDOKIYG","XOBKDYGUI","BKIXUYGDO","GOIXUBDKY","OGIKXYBUD","BDOKIGXUY","IYGDBUOXK","UDOIKYGXB","YUODGKXBI","XOGIDUBYK","IYDKXBOUG","YXBDKGIUO","XGYIKBUOD","YBGDXIKUO","IDUBGKYOX","OUKIGBDYX","IBXYOUGKD","XYOGDUIKB","XIOYDUGBK","IBXYGKDOU","KGBOUDIXY","UGDBYKOXI","OBYDUIXGK","XIKDUGBOY","XBIDGKOUY","XOUGBYDKI","GDIUYBOXK","IODKYXGBU","IGKYDUOXB","GBIDKYXOU","OKGYIDUXB","IGOUYBXDK","YDUXKOIBG","IXKBDOGUY","BXYODGKIU","UIXDGBYOK","KIDBYXUOG","DBUOIXGKY","DYGBUXKIO","IXDGKBUYO","YGUBXIKOD","UDGIOKYBX","YKBXUGOID","BXGYODIUK","XDYGKIOUB","DYUBXIOKG","GIUXKBODY","GKBDXYIOU","YGXOKDBUI","XUGBKIDYO","IUXKDBYGO","ODBKIGUXY","BXKOUGYID","XGUDOYBKI","IKDGOXYBU","OXIDUYGBK","BUXKIYGOD","KGYIXUBDO","IYGBODXUK","IYGUDKBOX","XKYODUGIB","DKXGYIOBU","YDOKGIXBU","DGKXOYBIU","BUDKYIXGO","UBIDYXOGK","GDOUKIBXY","BGOXIKDYU","XIODYUGKB","KGYIUOXBD","OXIYGUDBK","UOIBKGXYD","UKXBDYIGO","GYUOKBIDX","DBKIUOXGY","UOGIDBXKY","XDKUBIYOG","OXGBDIUKY","BKUXGIDOY","XBYGIDOKU","KIGUXOYBD","UIXOGBYKD","YBUDKGOXI","GXOBIUKYD","OXUDYGBKI","YOBGKXDIU","BKUYIXGOD","OGKUBDIYX","IXDKYBGUO","OYUGBIDKX","YDKXBIOGU","BIXKGUDYO","ODIKXUBYG","IGKUYBOXD","YKUGODIXB","UGBODXIYK","XIODKUGBY","XIGDYKBOU","YKXBGDOIU","DUXGOBIYK","DKOIBGUXY","DBOGUIXYK","XBIGDUYKO","IDBOYUKXG","BUODIYGKX","GIDXKBYOU","KDUYGOBXI","XUIDYGOBK","UDGIOKXYB","XKYBUODGI","XYIOKDBGU","XGKIYUBOD","XBYDIGKUO","XYUIDOBKG","XIYKOUDBG","GIDUKXOYB","XKYBIDOGU","IDUXYBOKG","GUKBDOYXI","KXIGDUOYB","YBKUOXGID","UGBOYKXID","YDOIBGXUK","UBDXKIYOG","IXBGDKYOU","IUDYBKGOX","UDYIXKGBO","ODIGXYUBK","BIXYKUDOG","KXUGBOIDY","KXBIUDGYO","DIUOGYBXK","IUBGXDYKO","YOBGIKXUD","DYIKOXGUB","BGYXIUODK","OYUKIDGBX","GKDXYIUBO","UGXKDIBOY","YIXUDOGKB","YDOIKGXUB","OXGYDIBKU","GKDBXIYUO","BGKOUIYXD","IDXGUBYKO","IGUDKOXBY","OGYIBUXDK","IDYOKUGBX","IKUXODGBY","KOIDGUXBY","DKIOUYGBX","OYIUDKBXG","KUIDYGBXO","UXBOGYDKI","BIUOGXKYD","KIUDXYBOG","DKGYOXIUB","GOUDIYXBK","ODBKYIUXG","UIKXBODYG","UYGXOBIKD","OXDGIKUBY","XGUIDYKBO","YXDOGBIKU","IYGKOUXDB","OXBIYKUDG","OYKIUDBGX","BOUDYXIKG","GDKXYIOBU","DYUIGKXBO","GUOBKXYID","UBYDOXKGI","BYDXIUGOK","XKIYUDBOG","XIYUDOGKB","XDUYIGOKB","GDBUIYKXO","IXOYDKGBU","DXIOBGUYK","IUGBXYODK","UKOYBGDXI","YOKUIDXBG","BGXUIYKOD","DIYKUOGBX","OBGUDXYIK","DUOYGIXBK","KDIXUBOGY","KBGDXUYOI","BKGDYOUIX","GUXBOYIDK","IODGXYBKU","OGXIYBDUK","DKIXGYBOU","DUGIOYKBX","BDKGIYXUO","OKDGUYXIB","IYKBGDXUO","DXKYGUOBI","BOKDGYXUI","IXUYKOGDB","UBOXDIGKY","OBXYGIKUD","DIXGYKBUO","DOBUYGKXI","DXBYUOGIK","KGXIDYUOB","KBXYDIOGU","GUXBIODYK","DKOUIBXGY","BYGUKOIXD","DGOKXUBYI","IXDGYBKOU","YKXIOGDUB","IDYGXUOBK","BDUXOYGIK","DBKXUIYGO","BDUGYKIOX","GDXOUIYKB","KDBGXUIOY","YGKDXIBUO","IOKXYDUBG","YIDOGKXBU","KGBYDOXUI","XUBGOKDIY","OGBDXUKYI","GKYBDXIOU","BKIDUXGYO","UIXDOYGKB","YOBDGXIKU","YXBKGOIDU","BKGIOYXUD","UGYBOXDKI","DYKGUXOIB","UXKIBYDOG","DXBOIYUKG","DXGBYKIUO","OIDKYUBGX","BUOIGDKXY","DXBGOKYIU","DUYBGKOXI","OKUIBYDXG","YXBKIGODU","OXKUIBYGD","UBGIOXDKY","XGOBUYDIK","IBUODYGXK","OUIKXBDYG","UXGKOIYDB","KGDUBIXOY","BGKYOIDXU","YXKUGIDBO","BDIGKOYXU","UGBYOIKDX","XYIOBKDGU","IOKYXUBGD","IKGOYXBDU","UDXBGYIOK","GUDBIXKOY","XDYOBGIUK","IGODYKBUX"]))